workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    BlackBox API:
        inputs:
            - location: https://staging-api.blckbox.dev/api-docs/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/blackbox/api/black-box-api
targets:
    blackboxlabs-sdk:
        target: typescript
        source: BlackBox API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/blackbox/api/black-box-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
